services:
  cdnpush:
    image: node:18-alpine
    container_name: cdnpush
    working_dir: /app
    volumes:
      - .:/app
      - /home/admin/domains/media:/media
    ports:
      - "3003:3003"
    environment:
      - IMAGE_PATH=/media
      - MAINAPI_URL=http://central_api:3000
    command: >
      sh -c "npm install && npm start"
    networks:
      - app_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  app_net:
    external: true
